import React from 'react';
import { FileInput, FileOutput, ArrowRight, Zap, Copy, GitMerge, Calendar, Hash, AlertCircle, CheckCircle } from 'lucide-react';

interface FieldMapping {
  targetField: string;
  targetPath: string;
  targetType: string;
  sourceFields: Array<{
    name: string;
    path: string;
    type: string;
  }>;
  transformationType: string;
  transformationDetails?: string;
  confidence?: number;
  autoGenerated?: boolean;
}

interface MappingVisualizerProps {
  sourceProfile: string;
  targetProfile: string;
  sourceFields: Array<{ name: string; type: string }>;
  targetFields: Array<{ name: string; type: string }>;
  mappings: FieldMapping[];
  unmappedSourceFields?: Array<{ name: string; type: string }>;
  unmappedTargetFields?: Array<{ name: string; type: string }>;
  autoGenerated?: boolean;
}

export default function MappingVisualizer({
  sourceProfile,
  targetProfile,
  sourceFields,
  targetFields,
  mappings,
  autoGenerated = false
}: MappingVisualizerProps) {
  
  // Build mapping lookups
  const mappingsByTarget = new Map<string, FieldMapping>();
  const mappingsBySource = new Map<string, FieldMapping>();
  
  mappings.forEach(m => {
    mappingsByTarget.set(m.targetField, m);
    m.sourceFields?.forEach(sf => mappingsBySource.set(sf.name, m));
  });

  const getTransformIcon = (type: string) => {
    switch (type) {
      case 'COPY': return <Copy size={14} />;
      case 'CONCAT': return <GitMerge size={14} />;
      case 'DATE_FORMAT': return <Calendar size={14} />;
      case 'SUBSTRING': return <Hash size={14} />;
      default: return <Zap size={14} />;
    }
  };

  const getTransformColor = (type: string) => {
    switch (type) {
      case 'COPY': return 'bg-green-100 text-green-700 border-green-300';
      case 'CONCAT': return 'bg-blue-100 text-blue-700 border-blue-300';
      case 'CONDITIONAL': return 'bg-amber-100 text-amber-700 border-amber-300';
      case 'INVOKE': return 'bg-purple-100 text-purple-700 border-purple-300';
      default: return 'bg-gray-100 text-gray-700 border-gray-300';
    }
  };

  const getTypeColor = (type: string) => {
    switch (type?.toLowerCase()) {
      case 'string': return 'text-green-600 bg-green-50';
      case 'integer': case 'int': case 'number': return 'text-blue-600 bg-blue-50';
      case 'double': case 'float': case 'decimal': return 'text-cyan-600 bg-cyan-50';
      case 'date': case 'datetime': return 'text-purple-600 bg-purple-50';
      case 'boolean': case 'bool': return 'text-amber-600 bg-amber-50';
      default: return 'text-gray-600 bg-gray-50';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-lg font-semibold text-jade-blue">Field Mappings</span>
          <span className="px-2 py-0.5 bg-jade-blue text-white text-xs rounded-full">
            {mappings.length} mapped
          </span>
        </div>
        {autoGenerated && (
          <div className="flex items-center gap-1 text-amber-600 text-sm bg-amber-50 px-3 py-1 rounded-full">
            <AlertCircle size={14} />
            Auto-generated suggestions
          </div>
        )}
      </div>

      {/* Legend */}
      <div className="flex gap-6 text-xs bg-gray-50 p-3 rounded-lg">
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-green-500"></div>
          <span>Direct Copy</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-blue-500"></div>
          <span>Transformation</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-amber-500"></div>
          <span>Conditional</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-3 h-3 rounded-full bg-gray-300"></div>
          <span>Unmapped</span>
        </div>
      </div>

      {/* Mapping Table - Clean Visual */}
      <div className="border rounded-lg overflow-hidden">
        <div className="grid grid-cols-[1fr,auto,1fr] bg-gray-100">
          <div className="p-3 font-semibold text-blue-700 flex items-center gap-2 border-r">
            <FileInput size={18} />
            {sourceProfile.split('/').pop()} 
            <span className="text-xs font-normal text-gray-500">({sourceFields.length} fields)</span>
          </div>
          <div className="p-3 font-semibold text-gray-600 flex items-center justify-center w-32">
            Transform
          </div>
          <div className="p-3 font-semibold text-green-700 flex items-center gap-2 border-l">
            <FileOutput size={18} />
            {targetProfile.split('/').pop()}
            <span className="text-xs font-normal text-gray-500">({targetFields.length} fields)</span>
          </div>
        </div>
        
        <div className="max-h-[400px] overflow-auto">
          {mappings.map((mapping, idx) => (
            <div 
              key={idx} 
              className="grid grid-cols-[1fr,auto,1fr] border-t hover:bg-green-50 transition-colors"
            >
              {/* Source Field(s) */}
              <div className="p-3 border-r">
                <div className="flex flex-wrap gap-1">
                  {mapping.sourceFields?.map((sf, sidx) => (
                    <div key={sidx} className="flex items-center gap-2 bg-blue-100 text-blue-800 px-2 py-1 rounded">
                      <span className="font-medium text-sm">{sf.name}</span>
                      <span className={`px-1.5 py-0.5 rounded text-xs ${getTypeColor(sf.type)}`}>
                        {sf.type}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
              
              {/* Transform */}
              <div className="p-3 flex items-center justify-center w-32">
                <div className={`flex items-center gap-1 px-2 py-1 rounded border ${getTransformColor(mapping.transformationType)}`}>
                  {getTransformIcon(mapping.transformationType)}
                  <span className="text-xs font-medium">{mapping.transformationType}</span>
                </div>
              </div>
              
              {/* Target Field */}
              <div className="p-3 border-l">
                <div className="flex items-center gap-2 bg-green-100 text-green-800 px-2 py-1 rounded w-fit">
                  <CheckCircle size={14} className="text-green-600" />
                  <span className="font-medium text-sm">{mapping.targetField}</span>
                  <span className={`px-1.5 py-0.5 rounded text-xs ${getTypeColor(mapping.targetType)}`}>
                    {mapping.targetType}
                  </span>
                </div>
                {mapping.autoGenerated && mapping.confidence && (
                  <div className="text-xs text-amber-600 mt-1">
                    {mapping.confidence}% confidence match
                  </div>
                )}
              </div>
            </div>
          ))}
          
          {mappings.length === 0 && (
            <div className="p-8 text-center text-gray-500">
              <AlertCircle size={32} className="mx-auto mb-2 opacity-50" />
              <p>No mappings found between these profiles</p>
            </div>
          )}
        </div>
      </div>

      {/* Unmapped Fields Section */}
      <div className="grid grid-cols-2 gap-4">
        {/* Unmapped Source Fields */}
        <div className="border rounded-lg overflow-hidden">
          <div className="bg-gray-100 p-3 font-semibold text-gray-700 flex items-center gap-2">
            <FileInput size={16} />
            Unmapped Source Fields
            <span className="text-xs font-normal bg-gray-200 px-2 py-0.5 rounded-full">
              {sourceFields.filter(f => !mappingsBySource.has(f.name)).length}
            </span>
          </div>
          <div className="max-h-40 overflow-auto p-2">
            <div className="flex flex-wrap gap-1">
              {sourceFields.filter(f => !mappingsBySource.has(f.name)).slice(0, 20).map((field, idx) => (
                <span key={idx} className="px-2 py-1 bg-gray-100 text-gray-600 rounded text-xs">
                  {field.name}
                </span>
              ))}
              {sourceFields.filter(f => !mappingsBySource.has(f.name)).length > 20 && (
                <span className="px-2 py-1 text-gray-500 text-xs">
                  +{sourceFields.filter(f => !mappingsBySource.has(f.name)).length - 20} more
                </span>
              )}
            </div>
          </div>
        </div>
        
        {/* Unmapped Target Fields */}
        <div className="border rounded-lg overflow-hidden">
          <div className="bg-gray-100 p-3 font-semibold text-gray-700 flex items-center gap-2">
            <FileOutput size={16} />
            Unmapped Target Fields
            <span className="text-xs font-normal bg-gray-200 px-2 py-0.5 rounded-full">
              {targetFields.filter(f => !mappingsByTarget.has(f.name)).length}
            </span>
          </div>
          <div className="max-h-40 overflow-auto p-2">
            <div className="flex flex-wrap gap-1">
              {targetFields.filter(f => !mappingsByTarget.has(f.name)).slice(0, 20).map((field, idx) => (
                <span key={idx} className="px-2 py-1 bg-gray-100 text-gray-600 rounded text-xs">
                  {field.name}
                </span>
              ))}
              {targetFields.filter(f => !mappingsByTarget.has(f.name)).length > 20 && (
                <span className="px-2 py-1 text-gray-500 text-xs">
                  +{targetFields.filter(f => !mappingsByTarget.has(f.name)).length - 20} more
                </span>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4">
        <div className="bg-blue-50 p-4 rounded-lg text-center border border-blue-200">
          <div className="text-3xl font-bold text-blue-600">{sourceFields.length}</div>
          <div className="text-sm text-blue-600">Source Fields</div>
        </div>
        <div className="bg-green-50 p-4 rounded-lg text-center border border-green-200">
          <div className="text-3xl font-bold text-green-600">{targetFields.length}</div>
          <div className="text-sm text-green-600">Target Fields</div>
        </div>
        <div className="bg-jade-blue bg-opacity-10 p-4 rounded-lg text-center border border-jade-blue border-opacity-30">
          <div className="text-3xl font-bold text-jade-blue">{mappings.length}</div>
          <div className="text-sm text-jade-blue">Mapped</div>
        </div>
        <div className="bg-amber-50 p-4 rounded-lg text-center border border-amber-200">
          <div className="text-3xl font-bold text-amber-600">
            {Math.round((mappings.length / Math.max(targetFields.length, 1)) * 100)}%
          </div>
          <div className="text-sm text-amber-600">Coverage</div>
        </div>
      </div>
    </div>
  );
}
